config/routes.rb
Blog::Application.routes.draw do

  resources :reports

  resources :pages

	get 'signup', to: 'users#new', as: 'signup'
	get 'login', to: 'sessions#new', as: 'login'
	get 'admin', to: 'sessions#new', as: 'login'
	get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions
	get 'cancel_registration', to: 'cancel_registration#new', as: 'cancel_registration'
  resources :cancel_registration

	get 'registrations/online', to: 'registrations#online', as: 'registrations/online'
  get 'about', to: 'pages#about', as: 'about'
	match 'reports/find_by_date', to: 'reports#find_by_date', as: 'reports/find_by_date'
	match 'all_registrations', to: 'registrations#all_registrations', as: 'all_registrations'
	match 'search', to: 'registrations#search', as: 'search'
	match 'registrations/find_by_class_date', to: 'registrations#find_by_class_date',
				as: 'registrations/find_by_class_date'
	match 'registrations/find_by_registration_date', to: 'registrations#find_by_registration_date',
				as: 'registrations/find_by_registration_date'
	match 'registrations/find_by_student_id', to: 'registrations#find_by_student_id',
				as: 'registrations/find_by_student_id'
	match 'registrations/find_by_name', to: 'registrations#find_by_name',
				as: 'registrations/find_by_name'

  resources :registrations do
		member do
			post 'toggle'
		end
	end

  resources :orientations do
		resources :registrations
	end

  root to: 'orientations#index'
	match '*path' => redirect('/')
end

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>
  <div class="actions">

    <%= f.submit :class => "btn btn-default" %>

  </div>
<% end %>

app/views/pages/about.html.erb
<h2>New Student Orientation Scheduling Application c2014</h2>
<p>Created by: Mark Locklear</p>

<ul>
  <li>https://bitbucket.org/marklocklear/nso</li>
  <li>cap deploy #push code from bitbucket to server</li>
  <li>cap deploy:migrate #migrate database</li>
  <li>cap seed #to run seed file</li>
  <li>rake send_reminder_emails #to run /lib/tasks/reminder_emails.rake</li>
  <li>rake create_registrations #to run /lib/tasks/create_registrations.rake</li>
  <li>configure reminder emails task via cron on prod in config/schedule.rb</li>
</ul>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page, :class => 'btn btn-default' %>
<%= link_to 'Back', pages_path, :class => 'btn btn-default' %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table class="table table-hover table-striped table-bordered">>
  <tr>
    <th>Name</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td><%= page.name %></td>
    <td><%= page.content %></td>
    <td><%= link_to 'Show', page, :class => 'btn btn-info' %></td>
    <td><%= link_to 'Edit', edit_page_path(page), :class => 'btn btn-warning' %></td>
    <td><%= link_to 'Destroy', page, :class => 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Page', new_page_path, :class => 'btn btn-default' %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path, :class => 'btn btn-default' %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @page.name %>
</p>

<p>
  <b>Content:</b>
  <%= @page.content %>
</p>


<%= link_to 'Edit', edit_page_path(@page), :class => 'btn btn-default' %>
<%= link_to 'Back', pages_path, :class => 'btn btn-default' %>