config/routes.rb
Blog::Application.routes.draw do

  resources :reports

  resources :pages

	get 'signup', to: 'users#new', as: 'signup'
	get 'login', to: 'sessions#new', as: 'login'
	get 'admin', to: 'sessions#new', as: 'login'
	get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions
	get 'cancel_registration', to: 'cancel_registration#new', as: 'cancel_registration'
  resources :cancel_registration

	get 'registrations/online', to: 'registrations#online', as: 'registrations/online'
  get 'about', to: 'pages#about', as: 'about'
	match 'reports/find_by_date', to: 'reports#find_by_date', as: 'reports/find_by_date'
	match 'all_registrations', to: 'registrations#all_registrations', as: 'all_registrations'
	match 'search', to: 'registrations#search', as: 'search'
	match 'registrations/find_by_class_date', to: 'registrations#find_by_class_date',
				as: 'registrations/find_by_class_date'
	match 'registrations/find_by_registration_date', to: 'registrations#find_by_registration_date',
				as: 'registrations/find_by_registration_date'
	match 'registrations/find_by_student_id', to: 'registrations#find_by_student_id',
				as: 'registrations/find_by_student_id'
	match 'registrations/find_by_name', to: 'registrations#find_by_name',
				as: 'registrations/find_by_name'

  resources :registrations do
		member do
			post 'toggle'
		end
	end

  resources :orientations do
		resources :registrations
	end

  root to: 'orientations#index'
	match '*path' => redirect('/')
end

app/models/orientation.rb
class Orientation < ActiveRecord::Base
	has_many :registrations
  attr_accessible :seats, :class_date, :class_time, :location

	validates_presence_of :class_date, :class_time, :location
  validates :seats, :numericality => { :greater_than_or_equal_to => 0 }

  def current_number_seats
		r = self.registrations.where(cancelled: false).count
    self.seats - r
  end

#depricated method in favor of is_not_past below
	def self.is_not_past_date(orientation)
		orientation.class_date >= Date.today
	end

  def self.is_not_past(orientation)
    date = orientation.class_date
    time = Time.parse(orientation.class_time)
    datetime = DateTime.parse([ date, time ].join(' '))
    datetime > Time.now
  end

	def friendly_date
		class_date.to_date.strftime('%A, %B %d')
	end

	def get_valid_registrations
		#return registrations where cancelled is false
		#self.registrations.where(cancelled: false).count
		Registration.where(cancelled: false, orientation_id: self).count
	end
end

app/controllers/orientations_controller.rb
class OrientationsController < ApplicationController
	before_filter :authorize, :except => [:index, :show]
  # GET /orientations
  # GET /orientations.json
  def index
    @orientations = Orientation.all
    @orientation_by_date = @orientations.group_by(&:class_date)
    @date = params[:date] ? Date.parse(params[:date]) : Date.today

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orientations }
    end
  end

  # GET /orientations/1
  # GET /orientations/1.json
  def show
    @orientation = Orientation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @orientation }
    end
  end

  # GET /orientations/new
  # GET /orientations/new.json
  def new
    @orientation = Orientation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @orientation }
    end
  end

  # GET /orientations/1/edit
  def edit
    @orientation = Orientation.find(params[:id])
  end

  # POST /orientations
  # POST /orientations.json
  def create
		from_date = Date.parse(params[:from_date])
		if params[:to_date] != '' #do this only if to_date is not empty
			to_date = Date.parse(params[:to_date])
			if params[:ignored_days] #do this if any of the days are checked
      	date_range = (from_date..to_date).to_a
				date_range.each do |r|
  				next if params[:ignored_days].include? r.wday.to_s
  				params[:orientation][:class_date] = r
  				@orientation = Orientation.new(params[:orientation])
  				@orientation.save
				end			

			else #else create an orientation for each day
				to_date = Date.parse(params[:to_date])
				from_date = Date.parse(params[:from_date])
      	date_range = (from_date..to_date).to_a
				date_range.each do |r|
					next if [0,6].include? r.wday #this excludes Sat/Sunday
					params[:orientation][:class_date] = r
					@orientation = Orientation.new(params[:orientation])
					@orientation.save
				end
			end
  	else #if to_date is empty just create a single orientation
      params[:orientation][:class_date] = params[:from_date]
    	@orientation = Orientation.new(params[:orientation])
    	@orientation.save
	  end

    respond_to do |format|
      if @orientation.save
        format.html { redirect_to orientations_path, notice: 'Orientation was successfully created.' }
        format.json { render json: @orientation, status: :created, location: @orientation }
      else
        format.html { render action: "new" }
        format.json { render json: @orientation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orientations/1
  # PUT /orientations/1.json
  def update
    @orientation = Orientation.find(params[:id])
		if @orientation.active == false #open orientation if its full
				@orientation.active = true
		end

    respond_to do |format|
      if @orientation.update_attributes(params[:orientation])
        format.html { redirect_to @orientation, notice: 'Orientation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @orientation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orientations/1
  # DELETE /orientations/1.json
  def destroy
    @orientation = Orientation.find(params[:id])
		registrations = @orientation.registrations
		registrations.each do |r|
			NsoMailer.after_cancellation_email(r).deliver
			r.destroy
		end
    @orientation.destroy

    respond_to do |format|
      format.html { redirect_to orientations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/orientations_helper.rb
module OrientationsHelper
end

app/views/orientations/_form.html.erb
<%= form_for(@orientation) do |f| %>
  <% if @orientation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@orientation.errors.count, "error") %> prohibited this orientation from being saved:</h2>

      <ul>
      <% @orientation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="from_date">
  <div id="from_date_text"></div>
		<input type="text" id="from_date" name="from_date"></input>
    <div id="date_error"></div>
  </div>
 <div class="field">
    Single <%= radio_button_tag 'selection', 'single', true %>
    Repeating Dates <%= radio_button_tag 'selection', 'repeating' %>
  </div>
  <div class="multiple_dates">
		<p>To Date</p>
    <%= text_field_tag "to_date" %>
		</br>
	Days to Exclude
	<% Date::DAYNAMES.each_with_index do |day_name, wday| %>
		<% if day_name == "Sunday" || day_name == "Saturday" %>
			<%= check_box_tag "ignored_days[]", wday, true %>
		<% else %>
			<%= check_box_tag "ignored_days[]", wday %>
		<% end %>
		<%= day_name %>
	<% end %>
  </div>
  <div class="field">
    <%= f.label :class_time %>
    <%= f.text_field :class_time %>
  </div>
  <div class="field">
    <%= f.label :seats %>
    <%= f.number_field :seats %>
  </div>
 	<div class="field">
    <%= f.label :Location%>
		<%= f.select :location, options_for_select(['Bailey 021', 'Balsam 217'], @orientation.location) %>

  </div>
  <div id="submit_button">
    <%= f.submit "Create Orientation", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/orientations/edit.html.erb
<h1>Editing orientation</h1>

<%= render 'form' %>

<%= link_to 'Show', @orientation, :class => "btn btn-default" %>&nbsp;
<%= link_to 'Back', orientations_path, :class => "btn btn-default" %>

app/views/orientations/index.html.erb
<div id="orientation">
<div id="legend">
  <i class="fa fa-check"></i>&nbsp;<h4>Available</h4>&nbsp;&nbsp;
  <i class="fa fa-minus-circle">&nbsp;</i><h4>Closed</h4>
</div>

 <h2 id="month">
    <%= link_to "<", date: @date.prev_month %>
    <%= @date.strftime("%B %Y") %>
    <%= link_to ">", date: @date.next_month %>
  </h2>
  <%= calendar @date do |date| %>
    <%= date.day %>
    <% if @orientation_by_date[date] %>
      <ul class="orientation-time">
        <% @orientation_by_date[date].each do |orientation| %>
   				<% if current_user %>
						<% if orientation.active? and Orientation.is_not_past(orientation) %>
          		<li class="class-available"><i class="fa fa-check"></i>&nbsp;
							<%= link_to orientation.class_time, new_orientation_registration_path(orientation) %>
									(<%= orientation.current_number_seats %>/<%= orientation.seats %>)</li>
        		<% else %>
							<li class="class-closed"><i class="fa fa-minus-circle"></i>&nbsp;<%= orientation.class_time %>
									(<%= orientation.current_number_seats %>/<%= orientation.seats %>)</li>
        		<% end %>
						<submit class="btn btn-mini" type="button">
						<%= link_to "VIEW", orientation_registrations_path(orientation) %></submit></li>
        	<% else %>
						<% if orientation.active? and Orientation.is_not_past(orientation) %>
          		<li class="class-available"><i class="fa fa-check"></i>&nbsp;
							<%= link_to orientation.class_time, new_orientation_registration_path(orientation) %>
        		<% else %>
							<li class="class-closed"><i class="fa fa-minus-circle"></i>&nbsp;<%= orientation.class_time %></li>
        		<% end %>
        	<% end %>
        <% end %>
      </ul>
    <% end %>
  <% end %>
</div>

app/views/orientations/new.html.erb
<h1>New orientation</h1>

<%= render 'form' %>

<%= link_to 'Back', orientations_path, :class => "btn btn-default" %>

app/views/orientations/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Date:</b>
  <%= @orientation.class_date %>
</p>
<p>
  <b>Time:</b>
  <%= @orientation.class_time %>
</p>
<p>
  <b>Slots:</b>
  <%= @orientation.seats %>
</p>


<%= link_to 'Edit', edit_orientation_path(@orientation), :class => "btn btn-default" %>&nbsp;
<%= link_to 'Back', orientations_path, :class => "btn btn-default" %>