config/routes.rb
Blog::Application.routes.draw do

  resources :reports

  resources :pages

	get 'signup', to: 'users#new', as: 'signup'
	get 'login', to: 'sessions#new', as: 'login'
	get 'admin', to: 'sessions#new', as: 'login'
	get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions
	get 'cancel_registration', to: 'cancel_registration#new', as: 'cancel_registration'
  resources :cancel_registration

	get 'registrations/online', to: 'registrations#online', as: 'registrations/online'
  get 'about', to: 'pages#about', as: 'about'
	match 'reports/find_by_date', to: 'reports#find_by_date', as: 'reports/find_by_date'
	match 'all_registrations', to: 'registrations#all_registrations', as: 'all_registrations'
	match 'search', to: 'registrations#search', as: 'search'
	match 'registrations/find_by_class_date', to: 'registrations#find_by_class_date',
				as: 'registrations/find_by_class_date'
	match 'registrations/find_by_registration_date', to: 'registrations#find_by_registration_date',
				as: 'registrations/find_by_registration_date'
	match 'registrations/find_by_student_id', to: 'registrations#find_by_student_id',
				as: 'registrations/find_by_student_id'
	match 'registrations/find_by_name', to: 'registrations#find_by_name',
				as: 'registrations/find_by_name'

  resources :registrations do
		member do
			post 'toggle'
		end
	end

  resources :orientations do
		resources :registrations
	end

  root to: 'orientations#index'
	match '*path' => redirect('/')
end

app/controllers/cancel_registration_controller.rb
class CancelRegistrationController < ApplicationController
  def new
  end

	def edit
		@registration = Registration.find_by_registration_cancellation_token!(params[:id])
	end

	def create
  	registration = Registration.find_all_by_email(params[:email]).last
  	if registration
			registration.send_cancellation_email
  		redirect_to root_url, :notice => "Email sent with cancellation instructions."
		end
	end
end

app/helpers/cancel_registration_helper.rb
module CancelRegistrationHelper
end

app/views/cancel_registration/edit.html.erb
<%= Mustache.render(Page.find_by_name("Cancel Confirmation Email").content, {:registration => @registration }).html_safe %>
<td><%= link_to 'Yes. Cancel my Registration', registration_path(@registration), :class => "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>

app/views/cancel_registration/new.html.erb
<%= form_tag cancel_registration_path, :method => :post do %>
  <div class="field">
		If you would like to cancel a registration please enter your registration email below. An email will be
		sent with further instructions.
    <%= label_tag :email %>
    <%= text_field_tag :email, params[:email] %>
  </div>
  <div class="actions"><%= submit_tag "Send Email", :class => "btn btn-primary" %></div>
<% end %>